services:
  discord-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    network_mode: host
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - /etc/localtime:/etc/localtime:ro
